### ISSUE TITLE
Bug with pano not initializing in I1 and P4

### ISSUE THREAD

**Issue by dbaldwin** [dbaldwin/DronePan#42]
This is a blocking bug:

https://www.facebook.com/groups/dronepan/permalink/255832421436013/

Let's figure out the root cause.

**Comment by chrissearle** [comment]
Really hoping its something we can switch/toggle. Odd that it works for some but not others if it's not a setting or mode.

**Comment by chrissearle** [comment]
Should we be checking isVirtualStickControlModeAvailable state of the FC?

**Comment by chrissearle** [comment]
Possible workaround in https://github.com/dbaldwin/DronePan/commit/6c9786362ffaaf4c7dbb46daac995e01aa291e7e

**Comment by chrissearle** [comment]
Comment from DJI:

"Our resetGimbal function only reset the Roll and Yaw for the Inspire 1. However, not for the pitch, we don’t rotate back to the 0 degree. We would add this detail to our documentation in the coming future version."

So - right now we work for I1 (and P4?) when the user is currently at pitch 0 but not otherwise.

The fix in https://github.com/dbaldwin/DronePan/commit/6c9786362ffaaf4c7dbb46daac995e01aa291e7e seems safe based on this.

**Comment by chrissearle** [comment]
Fixed
